server:
  port: 8082

spring:
  application:
    name: product-stock-service
  datasource:
    url: jdbc:h2:mem:stockdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    show-sql: false
  h2:
    console:
      enabled: true
  webservices:
    path: /ws
