server:
  port: 8081

spring:
  application:
    name: shop-management-service
  datasource:
    url: jdbc:h2:mem:shopdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    show-sql: false
  h2:
    console:
      enabled: true
  graphql:
    graphiql:
      enabled: true

feign:
  client:
    config:
      default:
        connectTimeout: 3000
        readTimeout: 5000
        loggerLevel: FULL

resilience4j:
  circuitbreaker:
    instances:
      stockReservation:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 20s
        permitted-number-of-calls-in-half-open-state: 3
